### ISSUE TITLE
cross-env don't seems to work

### ISSUE THREAD

**Issue by bl00m** [kentcdodds/cross-env#172]
- `cross-env` version: 5.1.3
- `node` version: 9.6.1
- `npm` version: 5.6.0
- `OS` Manjaro Linux 17.1.6

## package.json
```javascript
{
  "name": "cross-env-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "cross-env NODE_ENV=production echo $NODE_ENV",
    "test2": "NODE_ENV=production; echo $NODE_ENV",
    "test3": "cross-env-shell GREETING=Hi NAME=Joe \"echo $GREETING && echo $NAME\""
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cross-env": "^5.1.3"
  }
}
```
## tests
```bash
$ npm run test

> cross-env-test@1.0.0 test /tmp/banzai
> cross-env NODE_ENV=production echo $NODE_ENV


$ npm run test2

> cross-env-test@1.0.0 test2 /tmp/banzai
> NODE_ENV=production; echo $NODE_ENV

production
$ npm run test3

> cross-env-test@1.0.0 test3 /tmp/banzai
> cross-env-shell GREETING=Hi NAME=Joe "echo $GREETING && echo $NAME"



```

As you can see for `test` and `test3`, cross-env simply don't work here. The NODE_ENV variable is not set and echo just print an empty line.
`test2` use the classic way to set the variable and it works.

Am i missing something ?

**Comment by warm200** [comment]
same issue here

**Comment by warm200** [comment]
@bl00m   try this,  this pattern works for me, very well
{
  "scripts": {
    "parentScript": "cross-env GREET=\"Joe\" npm run childScript",
    "childScript": "cross-env-shell \"echo Hello $GREET\""
  }
}

**Comment by bl00m** [comment]
@warm200 Indeed, this one works for me too

**Comment by kentcdodds** [comment]
> The firsts examples I've reported still don't work and according to the README they should.

Which examples are from the README?

You stumbled upon a limitation that never reveals itself in practical use cases. It's how the shell works. When you execute this:

```
cross-env NODE_ENV=production echo $NODE_ENV
```

The `$NODE_ENV` will be evaluated and passed to the `cross-env` command like this:

```
cross-env NODE_ENV=production echo ""
```

There's nothing that cross-env can do about it. Luckily there's really no use-case for that anyway. If this were really what you'd wanted to do (use an environment variable in the same command you set it), then you could simply do:

```
echo production
```

What you _really_ care about is that the script you run is executed with the environment variables you set and that's what's supported by `cross-env`. There are no examples in the README which contradict this.

There are _some_ situations where you might want to use the environment variable in the same script it's set to, which is why `cross-env-shell` exists.

Good luck @bl00m :)

**Comment by kentcdodds** [comment]
Actually, if you'd like to add a FAQ or "Common Issues" section to the README citing this issue that would probably be helpful to others.

**Comment by bl00m** [comment]
Ok I understand, now I feel stupid not to have thought to that in the first place...
Thanks for your clear explanation, I don't know about the FAQ thing but I'll think about it

**Comment by iq9891** [comment]
I use nvm switch version, it does not take effect
