### ISSUE TITLE
Get en variable value from inline command?

### ISSUE THREAD

**Issue by sinedied** [kentcdodds/cross-env#55]
Can we assign env variables from command results?

In my package.json I have:
```
    "build": "cross-env PKG_VERSION=$(npm run version) ng build",
    "version": "node -p -e \"require('./package.json').version\""
```

Does this work on windows? (I only have a mac at hand for now)
Thanks

**Comment by kentcdodds** [comment]
I'm not sure whether that works properly on windows. But it's definitely outside of the scope of `cross-env` because the way it works on mac is what is inside `$()` will run before the rest of the script is run (so if you were to put a `console.log` in `cross-env`, you wouldn't see `$(npm run version)` at all, but instead you'd see the evaluated version).

Incidentally, for this specific scenario, you might consider using the environment variable `npm_package_version` which is set for you automatically when running npm scripts. ([Learn more](https://egghead.io/lessons/tools-use-package-json-variables-in-npm-scripts?course=how-to-use-npm-scripts-as-your-build-tool)).

Good luck!

**Comment by sinedied** [comment]
Thanks for the tip with `npm_package_version`, but with other use cases is there a way to get value from another command execution?

**Comment by kentcdodds** [comment]
I'm not sure about that. I don't know how you'd do `$(command)` on Windows. But in any case, that's definitely not in scope for cross-env I'm afraid. Best of luck to you!
