### ISSUE TITLE
no env has been set after I run cross-env

### ISSUE THREAD

**Issue by MeatPieYan** [kentcdodds/cross-env#60]
i have add a script in package json as below 
`"dev": "cross-env NODE_ENV=development nodemon ./server/server.dev.js --watch server --watch build --watch config ",`

but process.env.NODE_ENV returns undefined in node program. 
Is there anything wrong in my script.

i have also run cross-env in terminal. But i still got undefined. 

`robindeMacBook-Pro:20170109_11602_1 robin$ cross-env NODE_ENV=dev`
`robindeMacBook-Pro:20170109_11602_1 robin$ node`
`> process.env.NODE_ENV`
`undefined`
`> `

**Comment by kentcdodds** [comment]
I'm not sure why you're having trouble with `nodemon` because I believe that should forward the `env` of the process that `nodemon` spawns. But in any case that's definitely a `nodemon` bug.

`cross-env` will only set the environment variable for the process that it runs, not for your current shell. That's by design. For example, try this:

```
cross-env NODE_ENV=dev node
> process.env.NODE_ENV
'dev'
```

If you still have trouble with `nodemon`, then please file an issue there. Good luck!
